# Generated by Django 5.0.7 on 2024-08-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_product_alter_menuitem_image_alter_menuitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
