# Generated by Django 5.0.7 on 2024-08-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
